### ISSUE TITLE
PGN with clock data

### ISSUE THREAD

**Issue by sbernsto** [Destaq/chess-graph#60]
Is there a command line argument for the code to ignore the clock data in the pgn? From what I understand, PGN's can have clock data.  So when I try it with clock data, the graph looks very strange:
![image](https://github.com/Destaq/chess-graph/assets/6393618/16fd4246-9302-416f-8465-081dd6d37124)

**Comment by Destaq** [comment]
I'm afraid that there's no such flag -- hadn't realized that the files could contain such time data. I'd recommend that you "de-timeify" your PGNs using some regex or Python script; I'm sure some tool for this already exists.

If you'd like to make a PR and implement a flag / time stamp handling that would also be wonderful.

**Comment by sbernsto** [comment]
I am not going to claim to be a code guru, I know just enough to be very
dangerous.  Here is code to fix the issue. You can try it with the attached
pgn.
[image: image.png]

*Stephan Bernstorf*
